/**
 * The pure half of `pnpm tokens`: app.css text in, static/tokens.css text out.
 *
 * Split out from build-tokens-css.mjs so tokens-css.test.ts can run the real
 * transform against app.css and fail when the committed sheet is stale. A test
 * that re-implemented the extraction instead would be a third copy of the same
 * parsing rules, free to drift from the generator the way the generated sheet
 * drifted from app.css.
 */

/** Below this, app.css has changed shape and the extraction is not to be trusted. */
const MIN_ROOT_TOKENS = 50;

/**
 * Body of a top-level `selector { ... }` block, brace-matched.
 * @param {string} appCss
 * @param {string} selector
 * @returns {string}
 */
function block(appCss, selector) {
  const start = appCss.indexOf(`${selector} {`);
  if (start === -1) throw new Error(`app.css has no ${selector} block`);

  const open = appCss.indexOf('{', start);
  let depth = 0;
  for (let i = open; i < appCss.length; i++) {
    if (appCss[i] === '{') depth++;
    if (appCss[i] === '}') depth--;
    if (depth === 0) return appCss.slice(open + 1, i);
  }
  throw new Error(`${selector} block is unterminated`);
}

/**
 * Custom-property declarations only — comments and other rules are dropped.
 * @param {string} body
 * @returns {{ name: string, value: string }[]}
 */
function declarations(body) {
  return [...body.matchAll(/--([a-z0-9-]+):\s*([^;]+);/g)].map(([, name, value]) => ({
    name,
    value: value.trim(),
  }));
}

/**
 * @param {{ name: string, value: string }[]} tokens
 * @returns {string}
 */
const render = (tokens) => tokens.map((t) => `  --${t.name}: ${t.value};`).join('\n');

/**
 * @param {string} appCss contents of src/app.css
 * @returns {{ css: string, tokenCount: number, darkCount: number }}
 */
export function buildTokensCss(appCss) {
  const rootTokens = declarations(block(appCss, ':root'));
  const darkTokens = declarations(block(appCss, '.dark'));

  /**
   * --font-sans/--font-mono live in Tailwind's `@theme` block, not `:root`, so a
   * consumer linking this file would get the type scale with no families to hang
   * it on. They are lifted in deliberately; loading the webfonts is the
   * consumer's job, and the fallbacks in the value cover it if they don't.
   */
  const themeFonts = declarations(block(appCss, '@theme')).filter((t) =>
    t.name.startsWith('font-'),
  );

  if (rootTokens.length < MIN_ROOT_TOKENS) {
    throw new Error(`Only ${rootTokens.length} tokens found in :root — did app.css change shape?`);
  }

  const css = `/**
 * zhaoyu.io design tokens — GENERATED by scripts/build-tokens-css.mjs.
 * Do not edit: edit src/app.css and run \`pnpm tokens\`.
 *
 * Custom properties only. No resets, no component styles, no Tailwind.
 * Add \`class="dark"\` to <html> for the dark theme; omit it for light.
 * Fonts: values name Geist Sans / Geist Mono with system fallbacks — load the
 * webfonts yourself if you want them.
 */
:root {
${render(themeFonts)}
${render(rootTokens)}
}

.dark {
${render(darkTokens)}
}
`;

  return { css, tokenCount: themeFonts.length + rootTokens.length, darkCount: darkTokens.length };
}
